name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  animated_text_kit: ^4.2.2 
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.0
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
